# Generated by Django 3.2.11 on 2025-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('participant_phone_numbers', models.TextField(help_text='Comma-separated phone numbers of participants')),
                ('volunteer_phone_numbers', models.TextField(help_text='Comma-separated phone numbers of volunteers')),
            ],
        ),
    ]
